name: tatapoint_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  
  # TAMBAHKAN BARIS INI:
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

